image: "$CI_REGISTRY/linbit/linbit-admin-backend/test-image"

# Use cargo to test the project
test:cargo:
  variables:
    RUSTFLAGS: "-Zinstrument-coverage"
    LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --locked -- -Z unstable-options --format json | cargo2junit > results.xml
    - grcov . --binary-path ./target/debug/ -s . -t cobertura --branch --ignore-not-existing --ignore "*cargo*" -o coverage.xml
    - grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "*cargo*" -o coverage.lcov
    - lcov --summary coverage.lcov
  artifacts:
    reports:
      junit:
        - results.xml
      cobertura: coverage.xml

test:rustfmt:
  script:
    - cargo fmt -- --version && cargo fmt -- --print-config current .
    - cargo fmt -- --check
